.github/dependabot.yml, .github/workflows/docs.yml, .github/workflows/test.yml
Setup some actions for this repository. Also added a Dependabot config file to keep dependencies up to date.
=> Setup Github actions

src/bitmap.rs, src/nullable.rs, src/offset.rs, src/validity.rs
=> Fix Bitmap storage to match Arrow specification

Cargo.toml, README.md, src/bitmap.rs, src/buffer.rs, src/lib.rs, src/nullable.rs, src/offset.rs, src/primitive.rs
=> Remove bitvec dependency

.github/workflows/docs.yml
This fixes the artifact upload and should fix the docs deploy job.
bors r+
=> Fix docs job upload condition

README.md
=> Fix link to the deployed docs of main

.github/workflows/bench.yml, .github/workflows/docs.yml, .github/workflows/release.yml
=> Add deploy environments for crates.io and benchmark-results

.github/workflows/test.yml
=> Use nightly clippy in test workflow

benches/narrow/bitmap/iter.rs, narrow-derive/Cargo.toml, src/bitmap/fmt.rs, src/bitmap/iter.rs, src/bitmap/mod.rs
=> Fix clippy warnings

src/array/string.rs
Closes #48 by:
- Implementing `FromIterator<Option<...>>` for `StringArray<true>`
- Implementing `ValidityBitmap` for `StringArray<true>`
- Testing these implementations.
=> Support nullable string arrays

.github/workflows/release.yml
=> Use cargo publish directly instead of publish action

src/array/string.rs
=> Implement `ArrayType` for `str`

src/array/boolean.rs, src/array/fixed_size_primitive.rs, src/array/null.rs, src/array/string.rs, src/array/variable_size_binary.rs, src/bitmap/mod.rs, src/bitmap/validity.rs, src/buffer.rs, src/nullable.rs, src/offset/buffer.rs, src/offset/mod.rs
Result of trying different approaches for a `FixedSizeListArray` implementation.
=> Add some flexibility to `Nullable`

.github/workflows/release.yml
=> chore(ci): revert removal of permissions

src/array/string.rs, src/offset.rs, tests/derive.rs
For nullable data it should also flatten the option iterator.
=> fix: offset extend impl for nullable data

src/array/boolean.rs, src/array/fixed_size_primitive.rs, src/array/null.rs, src/array/string.rs, src/array/struct.rs, src/array/variable_size_binary.rs, src/array/variable_size_list.rs, src/bitmap/mod.rs, src/nullable.rs, src/offset.rs
=> feat: add non-nullable to nullable conversion

examples/parquet.rs, narrow-derive/src/struct.rs, src/arrow/array/struct.rs
This enables roundtripping through a parquet file.
=> feat: convert `StructArray` from `arrow_array::StructArray`

src/array/boolean.rs, src/array/fixed_size_list.rs, src/array/fixed_size_primitive.rs, src/array/string.rs, src/bitmap/mod.rs, src/offset.rs
Fixes new 1.75.0 clippy warnings.
=> chore: fix clippy 1.75.0 warnings

.github/workflows/release.yml
=> chore(ci): re-enable auto releases

.gitattributes, Cargo.toml, narrow-derive/Cargo.toml, narrow-derive/src/enum.rs, narrow-derive/src/enum/mod.rs, narrow-derive/tests/expand/enum/named/generic.expanded.rs, narrow-derive/tests/expand/enum/named/generic.rs, narrow-derive/tests/expand/enum/named/simple.expanded.rs, narrow-derive/tests/expand/enum/named/simple.rs, narrow-derive/tests/expand/enum/unit/const_generic.expanded.rs, narrow-derive/tests/expand/enum/unit/const_generic.rs, narrow-derive/tests/expand/enum/unit/simple.expanded.rs, narrow-derive/tests/expand/enum/unit/simple.rs, narrow-derive/tests/expand/enum/unnamed/generic.expanded.rs, narrow-derive/tests/expand/enum/unnamed/generic.rs, narrow-derive/tests/expand/enum/unnamed/simple.expanded.rs, narrow-derive/tests/expand/enum/unnamed/simple.rs, narrow-derive/tests/expand/enum/unnamed/where_clause.expanded.rs, narrow-derive/tests/expand/enum/unnamed/where_clause.rs, src/array/null.rs, src/array/union.rs, src/lib.rs, tests/derive.rs
Closes #85 and #90.
An initial version, derive support is a bit messy and not fully working with generics yet.
=> feat: add `UnionArray`

src/array/fixed_size_binary.rs, src/array/mod.rs, src/arrow/array/fixed_size_binary.rs, src/arrow/array/logical.rs, src/bitmap/mod.rs, src/logical/mod.rs, src/logical/uuid.rs
Includes some changes to `FixedSizeBinary` to make it work for `Uuid` with the refactored `LogicalArray`.
=> feat!: refactor `LogicalArray` and add `IntoIterator`

README.md
=> docs: add why section to `README`

src/arrow/array/fixed_size_binary.rs
- Make `From<FixedSizeBinaryArray<N, NULLABLE, Buffer>> for Arc<dyn arrow_array::Array>` generic over `NULLABLE`.
- Use default buffer type in tests.
=> refactor: clean up `arrow-rs` interop `FixedSizeBinaryArray` impls and tests

.github/workflows/test.yml, Cargo.toml, README.md, examples/basic.rs, narrow-derive/src/enum.rs, narrow-derive/tests/expand/enum/named/generic.expanded.rs, narrow-derive/tests/expand/enum/named/simple.expanded.rs, narrow-derive/tests/expand/enum/unit/const_generic.expanded.rs, narrow-derive/tests/expand/enum/unit/simple.expanded.rs, narrow-derive/tests/expand/enum/unnamed/generic.expanded.rs, narrow-derive/tests/expand/enum/unnamed/simple.expanded.rs, narrow-derive/tests/expand/enum/unnamed/where_clause.expanded.rs, src/array/union.rs
=> feat: implement `IntoIterator` for `UnionArray`

examples/basic.rs, src/logical/box.rs, src/logical/mod.rs
=> feat: add `ArrayType` impl for `Box<T>`

release-plz.toml
To only generate one changelog and one GitHub release.
=> chore(release): update release-plz config
