- .github/codecov.yml
- .github/workflows/test.yml
Adds a coverage job that collects source based coverage with grocv and uploads it to Codecov.
> Add coverage job with grcov

- .github/bors.toml
- .github/workflows/test.yml
- README.md
- src/array/dictionary.rs
- src/array/fixed_size_list.rs
- src/array/fixed_size_primitive.rs
- src/array/mod.rs
- src/array/string.rs
Bumps MSRV to 1.54 for `HashMap::into_values`. This also includes fixes for 1.54 Clippy warnings.
> Add DictionaryArray

- .github/workflows/test.yml
- Cargo.toml
- README.md
- narrow-derive/Cargo.toml
- narrow-derive/src/lib.rs
- src/array/boolean.rs
- src/array/dictionary.rs
- src/array/fixed_size_list.rs
- src/array/fixed_size_primitive.rs
- src/array/mod.rs
- src/array/null.rs
- src/array/string.rs
- src/array/struct.rs
- src/array/union.rs
- src/array/variable_size_binary.rs
- src/array/variable_size_list.rs
- src/bitmap.rs
- src/buffer.rs
- src/nullable.rs
- src/offset.rs
- src/validity.rs
- Removed `TryInto`/`TryFrom`/`FromIterator` use statements
- Use `array.into_iter()` instead of `iter().copied()`
> Migrate to 2021 edition

- src/array/null.rs
- src/buffer.rs
The goal is to enable `Array` derive support for zero-sized types like unit structs or enums with one variant.
> Modify NullArray to support Array derive for unit structs

- src/array/fixed_size_list.rs
The trait bound `Array` made no sense and should have been `ArrayType`. For example: `[u8; N]` should map to `FixedSizeListArray<Uint8Array<false>, N, M>`.
bors r+
> Fix ArrayType impl for Rust array types

- .github/workflows/docs.yml
Currently the doc deploy [removes the bench data](https://github.com/mbrobbel/narrow/commit/271063ad76ba1ec888c8cd3c43554c9b44ce5fb3#diff-3089b146cea15f1c76bbdc5e356539ecf051e7e052c03083da42ff2c7151a718). By setting `keep_files: true` this should no longer happen. An uninteded side-effect is that outdated doc output is not removed, but we can always add a workaround when that becomes a problem.
> Keep benchmark data when deploying docs

- .github/bors.toml
- .github/workflows/bench.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Cargo.toml
- rustfmt.toml
- src/bitmap/fmt.rs
- src/bitmap/iter.rs
- src/bitmap/mod.rs
- src/buffer.rs
- src/length.rs
- src/lib.rs
- src/null.rs
- src/nullable/mod.rs
- src/offset/mod.rs
In addition to the offset field on a Bitmap:
- add a `rustfmt.toml` with some nightly features enabled
- modify some workflows to run with a nightly compiler
- implement Extend for Bitmap.
> Add offset to Bitmap for zero-copy slicing on non-byte boundaries

- .github/dependabot.yml
> Ignore `dtolnay/rust-toolchain` updates

- .github/bors.toml
- .github/workflows/bench.yml
- .github/workflows/docs.yml
- .github/workflows/test.yml
Bors is being deprecated so removing its config in this PR and preparing to automate releases via [cargo-smart-release](https://crates.io/crates/cargo-smart-release) + [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
> chore(ci): remove bors

- .github/workflows/release.yml
- .github/workflows/test.yml
Replace the current release workflow that was based on pushing tags with one that uses [cargo-smart-release](https://crates.io/crates/cargo-smart-release) on pushes to main.
> chore(ci): update release workflow to use `cargo-smart-release`

- Cargo.toml
This is not supported with `cargo smart-release`.
> chore: remove workspace version

- .github/workflows/release.yml
If a release is not needed this prevents a failed status check. If the release failed for a different reason this also cancels it.
> chore(ci): cancel release if there is a failure

- .github/workflows/release.yml
Changelog generation fails if there is no need to publish a new version, so we should cancel then.
> chore(ci): cancel release if changelog generation fails

- src/array/boolean.rs
- src/array/fixed_size_primitive.rs
- src/array/null.rs
- src/array/string.rs
- src/array/struct.rs
- src/array/variable_size_binary.rs
- src/array/variable_size_list.rs
- src/offset.rs
When arrays are nullable they should provide access to the validity bitmap and the methods of the `ValidityBitmap` trait to get nullability information.
> fix: add missing `BitmapRef`, `BitmapRefMut` and `ValidityBitmap` implementations

- .github/workflows/release.yml
Another attempt to fix the release workflow. This splits the changelog generation and release and skips the release if the changelog command fails.
> fix(ci): skip release job if changelog job fails

- narrow-derive/src/struct/mod.rs
- narrow-derive/src/struct/unit.rs
- narrow-derive/src/struct/unnamed.rs
- narrow-derive/tests/expand/struct/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic_default.expanded.rs
- narrow-derive/tests/expand/struct/unit/simple.expanded.rs
- narrow-derive/tests/expand/struct/unit/where_clause.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/lifetime.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/lifetime.rs
- narrow-derive/tests/expand/struct/unnamed/nested.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/nested.rs
- narrow-derive/tests/expand/struct/unnamed/nested_generic.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/nested_generic.rs
- narrow-derive/tests/expand/struct/unnamed/simple.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/simple.rs
- src/array/struct.rs
- tests/derive.rs
```rust
#[derive(ArrayType, Default)]
struct Foo<'a>(u32, u16, &'a str);
#[derive(ArrayType, Default)]
struct Bar<'a>(Foo<'a>);
#[derive(ArrayType, Default)]
struct FooBar<'a, T>(Bar<'a>, T);
let input = [
FooBar(Bar(Foo(1, 2, "n")), false),
FooBar(Bar(Foo(1, 2, "arrow")), false),
];
let array = input.into_iter().collect::<StructArray<FooBar<_>>>();
assert_eq!(array.len(), 2);
let input = vec![
Some(vec![Some(FooBar(Bar(Foo(42, 0, "!"), 1234))]),
None,
Some(vec![None]),
Some(vec![None, None]),
];
let array = input
.into_iter()
.collect::<VariableSizeListArray<StructArray<FooBar<_>, true>, true>>();
assert_eq!(array.len(), 4);
```
> fix(derive): `ArrayType` derive for tuple structs

- .github/workflows/bench.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
The rustc version should be part of the cache key.
> chore(ci): fix Rust cache keys

- .github/codecov.yml
- .github/workflows/test.yml
It seems the tag was removed?
```console
Error: Unable to resolve action `codecov/codecov-action@v4`, unable to find version `v4`
```
Reverting.
> chore(deps): revert codecov/codecov-action from 4 to 3

- .github/workflows/test.yml
- Cargo.toml
- src/array/boolean.rs
- src/array/fixed_size_primitive.rs
- src/array/null.rs
- src/array/string.rs
- src/array/struct.rs
- src/array/variable_size_binary.rs
- src/array/variable_size_list.rs
- src/bitmap/mod.rs
- src/buffer.rs
- src/index.rs
- src/length.rs
- src/lib.rs
- src/nullable.rs
- src/offset.rs
- tests/derive.rs
Adds an `Index` trait to get items out of collections.
Also closes #57.
> Add `Index` trait

- narrow-derive/src/struct.rs
- narrow-derive/tests/expand/struct/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic_default.expanded.rs
- narrow-derive/tests/expand/struct/unit/self.expanded.rs
- narrow-derive/tests/expand/struct/unit/simple.expanded.rs
- narrow-derive/tests/expand/struct/unit/where_clause.expanded.rs
- src/array/null.rs
To support using `NullArray` for unit variants of enums in `UnionArrays`, this adds an `Item` associated type to the `Unit` trait, which converts into the type implementing `Unit`, allowing code generation of types for unit enum variants which implement `Unit` and convert to instances of the variants of the original enum.
> feat!: add item associated type to `Unit` trait

- .github/codecov.yml
- narrow-derive/src/struct.rs
- narrow-derive/tests/expand/struct/named/generic.expanded.rs
- narrow-derive/tests/expand/struct/named/generic_option.expanded.rs
- narrow-derive/tests/expand/struct/named/simple.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic_default.expanded.rs
- narrow-derive/tests/expand/struct/unit/self.expanded.rs
- narrow-derive/tests/expand/struct/unit/simple.expanded.rs
- narrow-derive/tests/expand/struct/unit/where_clause.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/generic.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/lifetime.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/multiple.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/nested.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/nested_generic.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/simple.expanded.rs
- src/array/mod.rs
- src/array/null.rs
- src/array/string.rs
- src/array/struct.rs
- src/array/union.rs
- src/offset.rs
This adds generics for offset element type (`i32` or `i64`) and union layout (sparse or dense) to the `Array` type constructor of the `ArrayType` trait.
This is not ideal without default types for the generics in a generic associated type, but the alternatives are worse (making `ArrayType` generic over these types with defaults).
> feat!: add `OffsetElement` and `UnionType` to the `Array` GAT of `ArrayType`

- Cargo.lock
- Cargo.toml
> chore: disable default features of `parquet` dependency

- .github/workflows/docs.yml
- Cargo.toml
To make sure the deployed docs of the main branch render required features.
> docs: add `docs.rs` metadata and set `docsrs` for main branch doc deploy

- src/array/mod.rs
The `FixedSize` bound was used when arrays were stored in `FixedSizePrimitiveArray`.
> fix: bound on `ArrayType` implementation for arrays

- Cargo.lock
- Cargo.toml
Bumps the `arrow` and `parquet` dependencies to `50.0.0`.
> chore(deps): bump arrow and parquet to `50.0.0`

- Cargo.lock
- Cargo.toml
- examples/parquet.rs
- src/array/boolean.rs
- src/array/fixed_size_list.rs
- src/array/fixed_size_primitive.rs
- src/array/mod.rs
- src/array/null.rs
- src/array/string.rs
- src/array/struct.rs
- src/array/variable_size_binary.rs
- src/array/variable_size_list.rs
- src/arrow/array/boolean.rs
- src/arrow/array/fixed_size_list.rs
- src/arrow/array/fixed_size_primitive.rs
- src/arrow/array/logical.rs
- src/arrow/array/mod.rs
- src/arrow/array/string.rs
- src/arrow/array/struct.rs
- src/arrow/array/variable_size_list.rs
- src/lib.rs
- src/logical/mod.rs
- src/logical/uuid.rs
- src/validity.rs
Introduces a `LogicalArray` to support storing logical (and extension) types in Arrow arrays.
It also adds a `uuid` feature that adds logical array support for `uuid::Uuid`.
```
cargo r --example parquet --features="arrow-rs derive uuid"
Finished dev [unoptimized + debuginfo] target(s) in 0.15s
Running `target/debug/examples/parquet`
From narrow StructArray to Arrow RecordBatch
+----+---+-------+--------------+----------+------------+---------------------------------+----------------------------------------------------+
| a  | b | c     | d            | e        | f          | g                               | h                                                  |
+----+---+-------+--------------+----------+------------+---------------------------------+-------------------------------------- …
```
> feat: `LogicalArray` to support logical types

- Cargo.toml
- narrow-derive/src/struct.rs
This prevents downstream crates from having to define an `arrow-rs` feature to compile the generated code.
> fix: use `narrow-derive` crate feature instead of compiled crate feature

- Cargo.lock
- src/array/null.rs
- src/arrow/array/mod.rs
- src/arrow/array/null.rs
Note that there is no support for nullable null arrays in `arrow-rs`.
> feat: add `arrow` `NullArray` interop

- narrow-derive/src/enum.rs
- narrow-derive/tests/expand/enum/named/generic.expanded.rs
- narrow-derive/tests/expand/enum/named/simple.expanded.rs
- narrow-derive/tests/expand/enum/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/enum/unit/simple.expanded.rs
- narrow-derive/tests/expand/enum/unnamed/generic.expanded.rs
- narrow-derive/tests/expand/enum/unnamed/simple.expanded.rs
- narrow-derive/tests/expand/enum/unnamed/where_clause.expanded.rs
- tests/derive.rs
This prevents users from having to bring the trait in scope when using the derive macro.
> fix: use fully qualified syntax for `VARIANTS` const in `ArrayType` impl

- .github/workflows/release.yml
- examples/parquet.rs
- narrow-derive/src/enum.rs
- src/array/struct.rs
- src/array/union.rs
- src/arrow/array/mod.rs
- src/arrow/array/null.rs
- src/arrow/array/struct.rs
- src/arrow/array/union.rs
- src/arrow/mod.rs
A very hacky solution to support writing `UnionArray`s to parquet files by implementing the `arrow-rs` interop to map to `arrow_array::StructArray`. 
It only works for `SparseLayout`, because I don't know if arrow and/or parquet support `StructArrays` with child arrays of different lengths. The union array is mapped to a struct array with two top level fields: `types` and `variants`, where `types` is the `Int8Array` and `variants` is a `StructArray` with the arrays of the different variants as fields.
Note that this is a temporary solution and I'll clean this up later.
Marking breaking change because this changes the default `UnionLayout` to `SparseLayout`. `StructArrayType`'s `ArrayType` needs generics associated types for `OffsetElement` and `UnionType`.
> feat!: add parquet write support for `UnionArray`

- src/array/fixed_size_binary.rs
- src/array/mod.rs
- src/arrow/array/fixed_size_binary.rs
- src/arrow/array/logical.rs
- src/arrow/array/mod.rs
- src/logical/uuid.rs
Adds a `FixedSizeBinaryArray` and use it for the logical array support for `Uuid`, to match the recommendation from [Arrow](https://arrow.apache.org/docs/format/Columnar.html#extensibility).
It just wraps `FixedSizeListArray<N, FixedSizePrimitiveArray<u8, false, Buffer>, NULLABLE, Buffer>`. We can't use `FixedSizePrimitiveArray<[u8; N], NULLABLE, Buffer>` because `FixedSize` is not implemented when the `arrow-rs` feature is enabled.
Closes #170.
The parquet example now outputs:
```console
From narrow StructArray to Arrow RecordBatch
+----+---+-------+--------------+----------+------------+---------------------------------+----------------------------------+---------------------------------------------------------------------+
| a  | b | c     | d            | e        | f          | g …
```
> feat!: add `FixedSizeBinaryArray` and use it for `Uuid`

- narrow-derive/src/struct.rs
- narrow-derive/tests/expand/struct/named/generic.expanded.rs
- narrow-derive/tests/expand/struct/named/generic_option.expanded.rs
- narrow-derive/tests/expand/struct/named/simple.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic_default.expanded.rs
- narrow-derive/tests/expand/struct/unit/self.expanded.rs
- narrow-derive/tests/expand/struct/unit/simple.expanded.rs
- narrow-derive/tests/expand/struct/unit/where_clause.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/generic.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/lifetime.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/multiple.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/nested.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/nested_generic.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/simple.expanded.rs
- narrow-derive/tests/expand/struct/unnamed/simple.rs
- src/array/string.rs
- src/array/struct.rs
- src/arrow/array/fixed_size_list.rs
- src/arrow/array/struct.rs
This is the first step to roundtrip `Vec<T>` -> `StructArray<T>` -> `Vec<T>` (`where T: StructArrayType`). This only works with fields that have array types that have `IntoIterator` implementations. Later I'll add support to iterate over items that reference data in the underlying arrays (e.g. getting a `&str` instead of `String` for a `String` field).
> feat: implement `IntoIterator` for `StructArray`

- src/array/fixed_size_list.rs
- src/array/struct.rs
- src/arrow/array/fixed_size_list.rs
Implements `IntoIterator` for `FixedSizeListArray` by introducing a `FixedSizeArrayChunk` struct that yields an iterator with items being (fixed size) arrays of the supplied iterator's items.
> feat: Implement `IntoIterator` for `FixedSizeListArray`

- narrow-derive/src/struct.rs
- narrow-derive/tests/expand/struct/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/struct/unit/const_generic_default.expanded.rs
- narrow-derive/tests/expand/struct/unit/where_clause.expanded.rs
Fields in the generated array struct definition copy the field visibility of the input struct.
> fix(derive): match field visibility in array struct definition

- src/arrow/array/string.rs
- src/arrow/array/variable_size_list.rs
- src/arrow/mod.rs
> fix: return `Large` variants of datatypes in `arrow::Array::as_field`

- examples/parquet.rs
- src/array/mod.rs
- src/array/variable_size_binary.rs
- src/arrow/array/mod.rs
- src/arrow/array/variable_size_binary.rs
- src/length.rs
- src/offset.rs
While converting between iterators over structs with a `Vec<u8>` field and a `VariableSizeBinaryArray` is already implemented, it doesn't work well yet for `Vec<Vec<u8>>` because it gets converted to a `ListArray` of `ListArrays` of `u8`'s. This introduces a wrapper type `VariableSizeBinary` around `Vec<u8>` to solve this problem.
> feat: Add support for variable size binary interop with arrow-rs

- src/array/mod.rs
- src/array/struct.rs
This impl was missing and caused the added test to fail compilation. This also removes the wrong `T: ArrayType<T>` bound for the `ArrayType` impl of `Option<Vec<Option<T>>>`.
The `ArrayType` impls should now cover:
- `Vec<T>`: non-nullable variable size list array, with non-nullable list items
- `Option<Vec<T>>`: nullable variable size list array, with non-nullable list items
- `Vec<Option<T>>`: non-nullable variable size list array, with nullable list items
- `Option<Vec<Option<T>>>`: nullable variable size list array, with nullable list items
> fix: add `ArrayType` for `Vec<Option<T>>` and fix `Option<Vec<Option<T>>>` impl

- .github/workflows/release.yml
Instead of releasing on every `push` to `main`, releases are now triggered manually. This is not to reduce release cadence, but to prevent multiple bumps when merging multiple PRs at once.
> ci: use `workflow_dispatch` instead of `push` to `main` for `release` workflow

- src/arrow/array/boolean.rs
- src/arrow/array/fixed_size_binary.rs
- src/arrow/array/fixed_size_list.rs
- src/arrow/array/fixed_size_primitive.rs
- src/arrow/array/string.rs
- src/arrow/array/struct.rs
- src/arrow/array/variable_size_binary.rs
- src/arrow/array/variable_size_list.rs
The `arrow` crate is not consistent in lazily allocating null buffers, so instead of panicking when trying to convert an `arrow-rs` array without a null buffer to a nullable `narrow` array, `narrow` allocates a null buffer (with all bits set).
> feat!: convert to nullable arrays from `arrow-rs` arrays without null buffers

- Cargo.lock
- Cargo.toml
- examples/parquet.rs
- src/logical/chrono.rs
- src/logical/mod.rs
Add logical array support for `chrono` types: `DateTime<Utc>`, `NaiveDateTime` and `NaiveTime`.
This does not include generics to control the different logical types supported by Arrow, and it also doesn't map to parquet temportal logical types yet. This needs more work (see #183). 
Part of #165.
> feat: add `chrono` feature

- Cargo.toml
- examples/parquet.rs
- src/lib.rs
- src/logical/chrono.rs
- src/logical/map.rs
- src/logical/mod.rs
- src/logical/uuid.rs
Follow up work: figure out how to support `HashMap<K, Option<V>>`, how to map to `arrow-rs`'s `MapArray` and adding implementations for the other map types in `std`.
> feat: add `map` feature with logical array support for `HashMap`

- src/arrow/array/union.rs
These impls are needed when using union fields in struct arrays and converting them to arrow struct arrays and recordbatches (these conversions rely on `dyn arrow_array::Array` conversions).
> feat: add `dyn arrow_array::Array` conversions for union arrays

- src/arrow/array/struct.rs
- tests/derive.rs
This PR adds the `schema()` function to `StructArray` that provides the means to obtain an `arrow_schema::Schema`. This is useful if you want to compare e.g. the schema of some Arrow `RecordBatch` before wrapping it as a Narrow `StructArray`.
This can be implemented in a more elegant way, which would prevent the allocations of buffers, but this works fine for now.
Also closes #187 well enough (for me).
> feat: Add function to StructArray that returns the Arrow schema

- examples/parquet.rs
- src/array/mod.rs
- src/array/variable_size_binary.rs
This fixes the added test. Because the bounds in the derived `IntoIterator` implementation for structs have bounds on the `Item` associated type of the `IntoIterator` impls of the fields, they must match, so for `VariableSizeBinary` we have to map via `LogicalArray`.
> feat: impl `LogicalArrayType` for `VariableSizeBinary` to fix `IntoIterator` when used in `StructArray`

- src/arrow/array/logical.rs
Maybe I should just write a macro to generate all these impls.
> feat: support `arrow` conversion of `LogicalArray` to `GenericListArray`

- Cargo.lock
- narrow-derive/Cargo.toml
Reverts mbrobbel/narrow#249. This release was yanked, causing the release workflow to break.
> chore(deps): revert bump of once_cell from 1.19.0 to 1.20.0

- src/arrow/array/boolean.rs
- src/arrow/array/fixed_size_binary.rs
- src/arrow/array/fixed_size_list.rs
- src/arrow/array/fixed_size_primitive.rs
- src/arrow/array/logical.rs
- src/arrow/array/null.rs
- src/arrow/array/string.rs
- src/arrow/array/struct.rs
- src/arrow/array/union.rs
- src/arrow/array/variable_size_binary.rs
- src/arrow/array/variable_size_list.rs
- src/arrow/mod.rs
A first step towards supporting overriding the data type for logical array types.
> feat: add `data_type` method to `arrow-rs` `Array` extension trait

- narrow-derive/src/struct.rs
- src/arrow/array/null.rs
- src/arrow/array/struct.rs
This changes the conversion from `arrow_array::StructArray` to `StructArray` to project the fields of the `StructArray` i.e. the conversion is no longer order dependent and selects the fields (by name) that are required to complete the conversion, panicking when a field for the target is missing in the source.
> feat!: project struct array fields in `arrow` conversion

- .gitignore
- Cargo.toml
- examples/tpch_lineitem.rs
This adds an example program of the LoC reduction when using `narrow` versus `arrow-rs` using the TPC-H lineitem table. In this example you go from ~110 lines to ~3 lines, which I think shows one of the benefits of using this crate in applications well.
To-do:
> test: Implement example showing LoC reduction in building RecordBatches

- .gitignore
- Cargo.lock
- Cargo.toml
- benches/narrow/bitmap/iter.rs
- benches/narrow/main.rs
- benches/narrow/versus/arrow/mod.rs
- benches/narrow/versus/arrow/primitive.rs
- benches/narrow/versus/mod.rs
This adds benchmarks that compare `narrow` versus `arrow-rs` when building an Arrow array of primitive values of varying bit lengths (`u8`, `u16`, `u32`, and `u64`) from an iterator.
> feat: Add benchmarks for primitive array building from an iterator

- .github/workflows/test.yml
- Cargo.toml
- README.md
- src/array/mod.rs
- src/array/string.rs
- src/array/struct.rs
- src/array/union.rs
- src/arrow/array/logical.rs
- src/arrow/array/struct.rs
- src/logical/mod.rs
I added 3 type aliases for commonly used complex types, greatly simplifying the type signatures making use of them.
> refactor: Simplified type signatures related to `ArrayType::Array`

- .github/workflows/release.yml
- Cargo.toml
- narrow-derive/Cargo.toml
- release-plz.toml
This helps to clean up the release process by using `release-plz`. This allows us to:
- Use a single workspace version for both crates
- Get a release PR that when merged creates a new release
- Setup branch protection and remove PAT secret
> chore: use `release-plz`

- src/fixed_size.rs
Fix the accidental supertrait removal in #294.
> fix: restore `ArrayType<Self>` supertrait for `FixedSize` trait

- examples/parquet.rs
- examples/tpch_lineitem.rs
- narrow-derive/src/enum.rs
- narrow-derive/src/struct.rs
- src/lib.rs
This should make it easier to use `narrow` i.e. users of the `arrow-rs` feature no longer need to add the arrow dependencies (with matching versions).
> feat: re-export arrow crates for `arrow-rs` feature

- .github/dependabot.yml
- .github/workflows/bench.yml
- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
These have better power-efficiency.
> ci: switch to `arm64` hosted runners

- .github/workflows/bench.yml
- .github/workflows/test.yml
- narrow-derive/Cargo.toml
- narrow-derive/tests/expand.rs
This means we no longer need `cargo-expand` in CI. These tests are mainly used for debugging macro output.
> chore: add custom `cfg` for expand test

- src/lib.rs
We don't need it because we use `doc_auto_cfg`.
> chore: remove `doc_cfg` feature

- narrow-derive/src/enum.rs
- narrow-derive/tests/expand/enum/named/generic.expanded.rs
- narrow-derive/tests/expand/enum/named/simple.expanded.rs
- narrow-derive/tests/expand/enum/unit/const_generic.expanded.rs
- narrow-derive/tests/expand/enum/unit/simple.expanded.rs
- narrow-derive/tests/expand/enum/unnamed/generic.expanded.rs
- narrow-derive/tests/expand/enum/unnamed/simple.expanded.rs
- narrow-derive/tests/expand/enum/unnamed/where_clause.expanded.rs
- src/array/union.rs
This is a continuation of https://github.com/mbrobbel/narrow/pull/244.
Since that's your branch, I can't push to it.
Of course, feel free to cherry pick this commit alone into that for merge.
Thanks again for sparing time to work on this :pray:
> feat: impl `Extend<T>` for `DenseUnionArray<T, ...>`

- src/buffer.rs
- src/collection.rs
- src/fixed_size.rs
- src/lib.rs
Adds buffer traits: `Buffer`, `BufferMut`, and `BufferAlloc`, and the `FixedSize` trait. Buffer are contiguous (in memory) collections (`Borrow<[T]>` for `T: FixedSize`).
> feat: add `Buffer` traits

- Cargo.toml
- benches/narrow/bitmap/iter.rs
- benches/narrow/main.rs
- src/bitmap/mod.rs
- src/bitmap/packed.rs
- src/bitmap/unpacked.rs
- src/buffer.rs
- src/collection.rs
- src/fixed_size.rs
- src/length.rs
- src/lib.rs
Adds `Bitmap` collection, storing 8 bits per byte. Removes mutable collection support, because supporting mutable iteration over a `Bitmap` requires streaming iterators, which I want to avoid for now.
> feat: add `Bitmap` collection

- src/bitmap/mod.rs
- src/buffer.rs
- src/collection.rs
- src/fixed_size.rs
A collection has one item type. Also renames the associated `RefItem` type of `Item` to `Ref` (and method to `as_ref`).
> refactor: use associated type for item types in `Collection`

- .github/workflows/release.yml
It doesn't work with `release-plz`, because the token can't be used to check if the crate is published.
> fix: revert trusted publishing

- src/bitmap/mod.rs
- src/buffer.rs
- src/collection.rs
- src/fixed_size.rs
- src/lib.rs
- src/validity.rs
Changes the `Collection` trait to support `View` types that borrow from the collection. This is required to make abstractions like `Offset` work as collections.
> feat!: refactor collection trait
